// Sumero-Akkadian cuneiform sign inventory.
// Unicode block: Cuneiform (U+12000..U+123FF).
//
// Each entry maps an ATF-style transliteration value (lowercase = syllabic
// Akkadian reading; UPPERCASE = Sumerian logographic reading) to a Unicode
// codepoint. Values are the common readings from the Labat / Borger / MZL
// tradition. Where a sign has many readings, only the most common are
// listed here.
//
// Determinatives are prefixes/suffixes marking semantic categories.
// In ATF they are written in superscript; in this app they are recognized
// via the {det} syntax (e.g. {d}enlil for DINGIR.enlil).

export interface SignEntry {
  glyph: string;
  category?: string;
  gloss?: string;
}

// Syllabic values (CV, VC, V, CVC). Lowercase.
export const SYLLABIC: Record<string, SignEntry> = {
  // vowels
  'a': { glyph: '\u{12000}', gloss: 'water; father (logogram A)' },
  'e': { glyph: '\u{1208A}', gloss: 'vowel e' },
  'i': { glyph: '\u{12146}', gloss: 'vowel i' },
  'u': { glyph: '\u{12308}', gloss: 'vowel u' },
  // CV syllables (consonant + vowel)
  'ba': { glyph: '\u{12040}', gloss: 'ba' },
  'be': { glyph: '\u{12040}', gloss: 'be (uses BA)' },
  'bi': { glyph: '\u{12049}', gloss: 'bi' },
  'bu': { glyph: '\u{1204A}', gloss: 'bu' },
  'da': { glyph: '\u{1206D}', gloss: 'da' },
  'de': { glyph: '\u{1206E}', gloss: 'de' },
  'di': { glyph: '\u{1206E}', gloss: 'di' },
  'du': { glyph: '\u{12073}', gloss: 'du (to go)' },
  'ga': { glyph: '\u{12100}', gloss: 'ga (milk)' },
  'ge': { glyph: '\u{12100}', gloss: 'ge (uses GA)' },
  'gi': { glyph: '\u{12108}', gloss: 'gi (reed)' },
  'gu': { glyph: '\u{12116}', gloss: 'gu (neck)' },
  'ha': { glyph: '\u{12129}', gloss: 'ha (fish)' },
  'hi': { glyph: '\u{12133}', gloss: 'hi (mix)' },
  'hu': { glyph: '\u{12137}', gloss: 'hu (bird)' },
  'ka': { glyph: '\u{12157}', gloss: 'ka (mouth)' },
  'ke': { glyph: '\u{12157}', gloss: 'ke (uses KA)' },
  'ki': { glyph: '\u{1215E}', gloss: 'ki (place, earth)' },
  'ku': { glyph: '\u{12170}', gloss: 'ku (to enter)' },
  'la': { glyph: '\u{12183}', gloss: 'la' },
  'li': { glyph: '\u{12189}', gloss: 'li' },
  'lu': { glyph: '\u{12195}', gloss: 'lu (man)' },
  'ma': { glyph: '\u{121A6}', gloss: 'ma' },
  'me': { glyph: '\u{121B7}', gloss: 'me' },
  'mi': { glyph: '\u{121B9}', gloss: 'mi' },
  'mu': { glyph: '\u{121BE}', gloss: 'mu (year, name)' },
  'na': { glyph: '\u{121D0}', gloss: 'na (stone)' },
  'ne': { glyph: '\u{121DE}', gloss: 'ne (fire)' },
  'ni': { glyph: '\u{121EF}', gloss: 'ni (oil, self)' },
  'nu': { glyph: '\u{12200}', gloss: 'nu (not)' },
  'pa': { glyph: '\u{1223E}', gloss: 'pa (branch)' },
  'pi': { glyph: '\u{12247}', gloss: 'pi (ear)' },
  'pu': { glyph: '\u{12248}', gloss: 'pu (well)' },
  'ra': { glyph: '\u{12249}', gloss: 'ra' },
  're': { glyph: '\u{12249}', gloss: 're (uses RA)' },
  'ri': { glyph: '\u{12263}', gloss: 'ri' },
  'ru': { glyph: '\u{12266}', gloss: 'ru' },
  'sa': { glyph: '\u{12273}', gloss: 'sa (sinew)' },
  'se': { glyph: '\u{12290}', gloss: 'se (grain, uses SHE)' },
  'si': { glyph: '\u{12295}', gloss: 'si (horn)' },
  'su': { glyph: '\u{122AE}', gloss: 'su (body)' },
  'sha': { glyph: '\u{1227A}', gloss: 'sha (heart)' },
  'she': { glyph: '\u{12290}', gloss: 'she (grain)' },
  'shi': { glyph: '\u{12295}', gloss: 'shi (uses SI)' },
  'shu': { glyph: '\u{1229E}', gloss: 'shu (hand)' },
  'ta': { glyph: '\u{122D3}', gloss: 'ta' },
  'te': { glyph: '\u{122E2}', gloss: 'te' },
  'ti': { glyph: '\u{122F1}', gloss: 'ti (arrow, life)' },
  'tu': { glyph: '\u{122FC}', gloss: 'tu' },
  'wa': { glyph: '\u{12000}', gloss: 'wa (uses A)' },
  'wi': { glyph: '\u{12146}', gloss: 'wi (uses I)' },
  'wu': { glyph: '\u{12308}', gloss: 'wu (uses U)' },
  'ya': { glyph: '\u{12000}', gloss: 'ya (uses A)' },
  'ye': { glyph: '\u{1208A}', gloss: 'ye (uses E)' },
  'yi': { glyph: '\u{12146}', gloss: 'yi (uses I)' },
  'za': { glyph: '\u{12327}', gloss: 'za' },
  'ze': { glyph: '\u{12327}', gloss: 'ze (uses ZA)' },
  'zi': { glyph: '\u{1232F}', gloss: 'zi (life-force)' },
  'zu': { glyph: '\u{12331}', gloss: 'zu (to know)' },
  // VC syllables (vowel + consonant)
  'ab': { glyph: '\u{12002}', gloss: 'ab (sea, cow)' },
  'ad': { glyph: '\u{1201D}', gloss: 'ad (father)' },
  'ag': { glyph: '\u{12007}', gloss: 'ag' },
  'ah': { glyph: '\u{12000}', gloss: 'ah (fallback)' },
  'ak': { glyph: '\u{12007}', gloss: 'ak (uses AG)' },
  'al': { glyph: '\u{1201F}', gloss: 'al (hoe)' },
  'am': { glyph: '\u{1202C}', gloss: 'am (wild ox)' },
  'an': { glyph: '\u{12038}', gloss: 'an (sky, god - DINGIR)' },
  'ap': { glyph: '\u{12002}', gloss: 'ap (uses AB)' },
  'ar': { glyph: '\u{12040}', gloss: 'ar (uses BA/AR)' },
  'as': { glyph: '\u{12047}', gloss: 'as (one wedge, ash)' },
  'ash': { glyph: '\u{12047}', gloss: 'ash (one)' },
  'at': { glyph: '\u{1201D}', gloss: 'at (uses AD)' },
  'az': { glyph: '\u{12000}', gloss: 'az (fallback)' },
  'ib': { glyph: '\u{12145}', gloss: 'ib (hip)' },
  'id': { glyph: '\u{12145}', gloss: 'id (uses IB)' },
  'ig': { glyph: '\u{12145}', gloss: 'ig (door)' },
  'ik': { glyph: '\u{12145}', gloss: 'ik (fallback)' },
  'il': { glyph: '\u{12148}', gloss: 'il (to raise)' },
  'im': { glyph: '\u{12150}', gloss: 'im (wind, clay)' },
  'in': { glyph: '\u{12154}', gloss: 'in (straw)' },
  'ip': { glyph: '\u{12145}', gloss: 'ip (uses IB)' },
  'ir': { glyph: '\u{12146}', gloss: 'ir (fallback to I)' },
  'is': { glyph: '\u{12148}', gloss: 'is (fallback)' },
  'ish': { glyph: '\u{12232}', gloss: 'ish (mountain, KUR)' },
  'it': { glyph: '\u{12145}', gloss: 'it (uses IB)' },
  'iz': { glyph: '\u{12148}', gloss: 'iz (fallback)' },
  'ub': { glyph: '\u{12305}', gloss: 'ub (corner)' },
  'ud': { glyph: '\u{12313}', gloss: 'ud (day, sun - UTU)' },
  'ug': { glyph: '\u{12313}', gloss: 'ug (uses UD)' },
  'uh': { glyph: '\u{12308}', gloss: 'uh (fallback)' },
  'uk': { glyph: '\u{12313}', gloss: 'uk (uses UD)' },
  'ul': { glyph: '\u{12317}', gloss: 'ul (star)' },
  'um': { glyph: '\u{1231D}', gloss: 'um (uses URU)' },
  'un': { glyph: '\u{1231D}', gloss: 'un (people, uses URU)' },
  'up': { glyph: '\u{12305}', gloss: 'up (uses UB)' },
  'ur': { glyph: '\u{12328}', gloss: 'ur (dog)' },
  'us': { glyph: '\u{1232E}', gloss: 'us (to lean)' },
  'ush': { glyph: '\u{12329}', gloss: 'ush (foundation)' },
  'ut': { glyph: '\u{12313}', gloss: 'ut (uses UD)' },
  'uz': { glyph: '\u{12308}', gloss: 'uz (fallback)' },
  // Common CVC syllables
  'bad': { glyph: '\u{12041}', gloss: 'bad (wall)' },
  'bal': { glyph: '\u{12042}', gloss: 'bal (spindle)' },
  'bar': { glyph: '\u{12043}', gloss: 'bar (outer)' },
  'bat': { glyph: '\u{12041}', gloss: 'bat (uses BAD)' },
  'bir': { glyph: '\u{1204C}', gloss: 'bir' },
  'dab': { glyph: '\u{1206D}', gloss: 'dab (uses DA)' },
  'dam': { glyph: '\u{12071}', gloss: 'dam (spouse)' },
  'dan': { glyph: '\u{12073}', gloss: 'dan (mighty)' },
  'dar': { glyph: '\u{12074}', gloss: 'dar' },
  'dim': { glyph: '\u{12079}', gloss: 'dim (pillar)' },
  'din': { glyph: '\u{1207B}', gloss: 'din (wine)' },
  'dub': { glyph: '\u{1207F}', gloss: 'dub (tablet)' },
  'dug': { glyph: '\u{12082}', gloss: 'dug (jar)' },
  'dul': { glyph: '\u{12073}', gloss: 'dul (uses DU)' },
  'dur': { glyph: '\u{12089}', gloss: 'dur (bond)' },
  'gal': { glyph: '\u{12106}', gloss: 'gal (great)' },
  'gan': { glyph: '\u{12107}', gloss: 'gan (field)' },
  'gar': { glyph: '\u{12111}', gloss: 'gar (to place)' },
  'gaz': { glyph: '\u{12112}', gloss: 'gaz (crush)' },
  'gid': { glyph: '\u{12108}', gloss: 'gid (uses GI)' },
  'gir': { glyph: '\u{12114}', gloss: 'gir (dagger)' },
  'gud': { glyph: '\u{1211E}', gloss: 'gud (bull)' },
  'gul': { glyph: '\u{1211F}', gloss: 'gul (destroy)' },
  'gur': { glyph: '\u{12121}', gloss: 'gur (return)' },
  'had': { glyph: '\u{12129}', gloss: 'had (uses HA)' },
  'hal': { glyph: '\u{1212E}', gloss: 'hal (share)' },
  'har': { glyph: '\u{12130}', gloss: 'har (ring)' },
  'hul': { glyph: '\u{12137}', gloss: 'hul (evil, uses HU)' },
  'kab': { glyph: '\u{12157}', gloss: 'kab (uses KA)' },
  'kal': { glyph: '\u{12159}', gloss: 'kal (mighty)' },
  'kam': { glyph: '\u{1215A}', gloss: 'kam' },
  'kan': { glyph: '\u{12157}', gloss: 'kan (uses KA)' },
  'kar': { glyph: '\u{1215F}', gloss: 'kar (quay)' },
  'kib': { glyph: '\u{12162}', gloss: 'kib' },
  'kid': { glyph: '\u{12163}', gloss: 'kid (mat)' },
  'kin': { glyph: '\u{12165}', gloss: 'kin (work)' },
  'kir': { glyph: '\u{12166}', gloss: 'kir' },
  'kul': { glyph: '\u{12170}', gloss: 'kul (uses KU)' },
  'kum': { glyph: '\u{12175}', gloss: 'kum' },
  'kur': { glyph: '\u{1217D}', gloss: 'kur (mountain, land)' },
  'lah': { glyph: '\u{12183}', gloss: 'lah (uses LA)' },
  'lal': { glyph: '\u{12184}', gloss: 'lal (small)' },
  'lam': { glyph: '\u{12185}', gloss: 'lam' },
  'lil': { glyph: '\u{12189}', gloss: 'lil (uses LI)' },
  'mah': { glyph: '\u{1219C}', gloss: 'mah (exalted)' },
  'mal': { glyph: '\u{121A6}', gloss: 'mal (uses MA)' },
  'man': { glyph: '\u{121AC}', gloss: 'man (two/twenty)' },
  'mar': { glyph: '\u{121AE}', gloss: 'mar (west)' },
  'mash': { glyph: '\u{121B2}', gloss: 'mash (twin)' },
  'mer': { glyph: '\u{121B7}', gloss: 'mer (uses ME)' },
  'mes': { glyph: '\u{121B8}', gloss: 'mes (hero, plural)' },
  'mud': { glyph: '\u{121C2}', gloss: 'mud (blood)' },
  'mun': { glyph: '\u{121BE}', gloss: 'mun (salt, uses MU)' },
  'mut': { glyph: '\u{121C2}', gloss: 'mut (fallback)' },
  'nab': { glyph: '\u{121D0}', gloss: 'nab (uses NA)' },
  'nad': { glyph: '\u{121D1}', gloss: 'nad (lie down)' },
  'nag': { glyph: '\u{121D5}', gloss: 'nag (drink)' },
  'nam': { glyph: '\u{121D9}', gloss: 'nam (fate)' },
  'nap': { glyph: '\u{121D0}', gloss: 'nap (uses NA)' },
  'nar': { glyph: '\u{121DA}', gloss: 'nar (musician)' },
  'nim': { glyph: '\u{121F0}', gloss: 'nim (high)' },
  'nin': { glyph: '\u{121F4}', gloss: 'nin (lady)' },
  'nir': { glyph: '\u{121FA}', gloss: 'nir (prince)' },
  'nun': { glyph: '\u{12201}', gloss: 'nun (prince)' },
  'pad': { glyph: '\u{1223E}', gloss: 'pad (portion, uses PA)' },
  'pag': { glyph: '\u{1223E}', gloss: 'pag (uses PA)' },
  'pah': { glyph: '\u{1223E}', gloss: 'pah (uses PA)' },
  'pal': { glyph: '\u{1223E}', gloss: 'pal (uses PA)' },
  'par': { glyph: '\u{12243}', gloss: 'par' },
  'pat': { glyph: '\u{1223E}', gloss: 'pat (uses PA)' },
  'pir': { glyph: '\u{12247}', gloss: 'pir (uses PI)' },
  'puh': { glyph: '\u{12248}', gloss: 'puh (uses PU)' },
  'rad': { glyph: '\u{12249}', gloss: 'rad (uses RA)' },
  'rah': { glyph: '\u{12249}', gloss: 'rah (uses RA)' },
  'sag': { glyph: '\u{12295}', gloss: 'sag (head)' },
  'sal': { glyph: '\u{12197}', gloss: 'sal (woman)' },
  'sam': { glyph: '\u{12274}', gloss: 'sam (buy)' },
  'sar': { glyph: '\u{12279}', gloss: 'sar (garden, write)' },
  'shab': { glyph: '\u{1227A}', gloss: 'shab (uses SHA)' },
  'shag': { glyph: '\u{1227A}', gloss: 'shag (uses SHA)' },
  'sham': { glyph: '\u{1228F}', gloss: 'sham' },
  'shar': { glyph: '\u{1228F}', gloss: 'shar (totality)' },
  'shag2': { glyph: '\u{1227A}', gloss: 'shag2' },
  'shim': { glyph: '\u{12296}', gloss: 'shim (aromatic)' },
  'shir': { glyph: '\u{12295}', gloss: 'shir (uses SI)' },
  'shu2': { glyph: '\u{1229F}', gloss: 'shu2' },
  'shul': { glyph: '\u{1229E}', gloss: 'shul (young man, uses SHU)' },
  'shum': { glyph: '\u{122A5}', gloss: 'shum (garlic)' },
  'shur': { glyph: '\u{122A9}', gloss: 'shur (rain)' },
  'sig': { glyph: '\u{12295}', gloss: 'sig (thin, uses SI)' },
  'sug': { glyph: '\u{122AE}', gloss: 'sug (marsh, uses SU)' },
  'sur': { glyph: '\u{122BE}', gloss: 'sur' },
  'tab': { glyph: '\u{122C5}', gloss: 'tab (double)' },
  'tag': { glyph: '\u{122D3}', gloss: 'tag (touch, uses TA)' },
  'tah': { glyph: '\u{122D3}', gloss: 'tah (uses TA)' },
  'tak': { glyph: '\u{122D3}', gloss: 'tak (uses TA)' },
  'tal': { glyph: '\u{122D3}', gloss: 'tal (uses TA)' },
  'tam': { glyph: '\u{122D3}', gloss: 'tam (uses TA)' },
  'tan': { glyph: '\u{122D3}', gloss: 'tan (uses TA)' },
  'tar': { glyph: '\u{122E0}', gloss: 'tar (cut)' },
  'tim': { glyph: '\u{122F1}', gloss: 'tim (uses TI)' },
  'tur': { glyph: '\u{122FE}', gloss: 'tur (small, child)' },
  'zag': { glyph: '\u{12327}', gloss: 'zag (side, uses ZA)' },
  'zal': { glyph: '\u{12327}', gloss: 'zal (uses ZA)' },
  'zar': { glyph: '\u{12327}', gloss: 'zar (uses ZA)' },
  'zid': { glyph: '\u{1232F}', gloss: 'zid (true, uses ZI)' },
  'zig': { glyph: '\u{1232F}', gloss: 'zig (uses ZI)' },
  'zik': { glyph: '\u{1232F}', gloss: 'zik (uses ZI)' },
  'zil': { glyph: '\u{1232F}', gloss: 'zil (uses ZI)' },
  'zim': { glyph: '\u{1232F}', gloss: 'zim (uses ZI)' },
  'zir': { glyph: '\u{1232F}', gloss: 'zir (uses ZI)' },
  'zur': { glyph: '\u{12331}', gloss: 'zur (uses ZU)' },
};

// Logograms: Sumerian words. Uppercase in ATF convention.
// In Akkadian text, a logogram stands for the Akkadian equivalent
// (e.g. LUGAL is written but read as sharrum, "king").
export const LOGOGRAM: Record<string, SignEntry> = {
  'A': { glyph: '\u{12000}', gloss: 'water, seed' },
  'AB': { glyph: '\u{12002}', gloss: 'sea, cow' },
  'AD': { glyph: '\u{1201D}', gloss: 'father' },
  'AN': { glyph: '\u{12038}', gloss: 'sky, god (also DINGIR)' },
  'DINGIR': { glyph: '\u{12038}', gloss: 'god (same sign as AN)' },
  'ANSHE': { glyph: '\u{1203B}', gloss: 'donkey' },
  'APIN': { glyph: '\u{12040}', gloss: 'plow' },
  'BAD': { glyph: '\u{12041}', gloss: 'wall, open' },
  'BAR': { glyph: '\u{12043}', gloss: 'half, outer' },
  'DAM': { glyph: '\u{12071}', gloss: 'spouse' },
  'DINGIR2': { glyph: '\u{12038}', gloss: 'god (variant)' },
  'DU': { glyph: '\u{12073}', gloss: 'to go' },
  'DUB': { glyph: '\u{1207F}', gloss: 'tablet' },
  'DUG': { glyph: '\u{12082}', gloss: 'jar' },
  'E': { glyph: '\u{1208A}', gloss: 'house' },
  'E2': { glyph: '\u{1208D}', gloss: 'house (temple)' },
  'EN': { glyph: '\u{12097}', gloss: 'lord' },
  'ENSI': { glyph: '\u{1209C}', gloss: 'city ruler' },
  'ERIN': { glyph: '\u{120A5}', gloss: 'troops' },
  'GA': { glyph: '\u{12100}', gloss: 'milk' },
  'GAL': { glyph: '\u{12106}', gloss: 'great' },
  'GAN': { glyph: '\u{12107}', gloss: 'field' },
  'GAR': { glyph: '\u{12111}', gloss: 'to place, form' },
  'GESHTIN': { glyph: '\u{12111}', gloss: 'wine (uses GAR family)' },
  'GI': { glyph: '\u{12108}', gloss: 'reed' },
  'GIG': { glyph: '\u{12113}', gloss: 'sick' },
  'GIR': { glyph: '\u{12114}', gloss: 'foot, dagger' },
  'GISH': { glyph: '\u{12117}', gloss: 'wood, tree' },
  'GU': { glyph: '\u{12116}', gloss: 'neck, ox' },
  'GUD': { glyph: '\u{1211E}', gloss: 'bull' },
  'GUR': { glyph: '\u{12121}', gloss: 'to return; capacity unit' },
  'HA': { glyph: '\u{12129}', gloss: 'fish' },
  'HAR': { glyph: '\u{12130}', gloss: 'ring' },
  'HI': { glyph: '\u{12133}', gloss: 'mixed, glow' },
  'HU': { glyph: '\u{12137}', gloss: 'bird' },
  'I': { glyph: '\u{12146}', gloss: 'cry out' },
  'ID': { glyph: '\u{12145}', gloss: 'river' },
  'IGI': { glyph: '\u{1214A}', gloss: 'eye, face' },
  'IL': { glyph: '\u{12148}', gloss: 'to raise' },
  'IM': { glyph: '\u{12150}', gloss: 'wind, clay, storm' },
  'IN': { glyph: '\u{12154}', gloss: 'straw' },
  'INIM': { glyph: '\u{12157}', gloss: 'word (uses KA)' },
  'KA': { glyph: '\u{12157}', gloss: 'mouth' },
  'KALAM': { glyph: '\u{1215C}', gloss: 'the Land (Sumer)' },
  'KI': { glyph: '\u{1215E}', gloss: 'earth, place' },
  'KIN': { glyph: '\u{12165}', gloss: 'work, task' },
  'KU': { glyph: '\u{12170}', gloss: 'to sit, enter' },
  'KUR': { glyph: '\u{1217D}', gloss: 'mountain, land, foreign land' },
  'LA': { glyph: '\u{12183}', gloss: 'to hang' },
  'LI': { glyph: '\u{12189}', gloss: 'juniper' },
  'LU': { glyph: '\u{12195}', gloss: 'man, person' },
  'LU2': { glyph: '\u{12195}', gloss: 'man (determinative form)' },
  'LUGAL': { glyph: '\u{12198}', gloss: 'king' },
  'MA': { glyph: '\u{121A6}', gloss: 'land, country' },
  'MAH': { glyph: '\u{1219C}', gloss: 'exalted' },
  'MASH': { glyph: '\u{121B2}', gloss: 'twin, kid' },
  'ME': { glyph: '\u{121B7}', gloss: 'divine essence' },
  'MES': { glyph: '\u{121B8}', gloss: 'plural marker; hero' },
  'MU': { glyph: '\u{121BE}', gloss: 'year, name' },
  'MUNUS': { glyph: '\u{12197}', gloss: 'woman' },
  'NA': { glyph: '\u{121D0}', gloss: 'stone' },
  'NAM': { glyph: '\u{121D9}', gloss: 'fate, office' },
  'NE': { glyph: '\u{121DE}', gloss: 'fire' },
  'NI': { glyph: '\u{121EF}', gloss: 'oil, self' },
  'NIN': { glyph: '\u{121F4}', gloss: 'lady, queen' },
  'NU': { glyph: '\u{12200}', gloss: 'not; man (variant)' },
  'NUN': { glyph: '\u{12201}', gloss: 'prince; Eridu' },
  'PA': { glyph: '\u{1223E}', gloss: 'branch, staff' },
  'PI': { glyph: '\u{12247}', gloss: 'ear' },
  'RA': { glyph: '\u{12249}', gloss: 'to beat, strike' },
  'SAG': { glyph: '\u{12295}', gloss: 'head' },
  'SAR': { glyph: '\u{12279}', gloss: 'garden; to write' },
  'SHA': { glyph: '\u{1227A}', gloss: 'heart, middle' },
  'SHE': { glyph: '\u{12290}', gloss: 'grain, barley' },
  'SHU': { glyph: '\u{1229E}', gloss: 'hand' },
  'SI': { glyph: '\u{12295}', gloss: 'horn; to fill' },
  'SU': { glyph: '\u{122AE}', gloss: 'body, flesh' },
  'TA': { glyph: '\u{122D3}', gloss: 'from' },
  'TE': { glyph: '\u{122E2}', gloss: 'approach, cheek' },
  'TI': { glyph: '\u{122F1}', gloss: 'rib, arrow, life' },
  'TU': { glyph: '\u{122FC}', gloss: 'to bring in' },
  'TUR': { glyph: '\u{122FE}', gloss: 'small, child' },
  'U': { glyph: '\u{12308}', gloss: 'ten; plant' },
  'UD': { glyph: '\u{12313}', gloss: 'day, sun' },
  'UTU': { glyph: '\u{12313}', gloss: 'sun-god (same sign as UD)' },
  'UM': { glyph: '\u{12315}', gloss: 'grandmother' },
  'UN': { glyph: '\u{1231D}', gloss: 'people (uses URU)' },
  'UR': { glyph: '\u{12328}', gloss: 'dog; hero' },
  'URU': { glyph: '\u{1231D}', gloss: 'city' },
  'ZA': { glyph: '\u{12327}', gloss: 'you; stone' },
  'ZI': { glyph: '\u{1232F}', gloss: 'life, breath, soul' },
  'ZU': { glyph: '\u{12331}', gloss: 'to know; tooth' },
};

// Determinatives: semantic prefixes/suffixes.
// Key in ATF is the short code that appears in {braces}.
// Convention: {d} = DINGIR (before divine names), {m} = disz (before male
// personal names), {f} = MUNUS (before female), {kur} = KUR (before lands),
// {uru} = URU (before cities), etc.
export const DETERMINATIVE: Record<string, SignEntry> = {
  'd': { glyph: '\u{12038}', gloss: 'DINGIR: divine' },
  'D': { glyph: '\u{12038}', gloss: 'DINGIR: divine' },
  'dingir': { glyph: '\u{12038}', gloss: 'DINGIR: divine' },
  'm': { glyph: '\u{12079}', gloss: 'DISH: male personal name' },
  'disz': { glyph: '\u{12079}', gloss: 'DISH: male personal name' },
  'f': { glyph: '\u{12197}', gloss: 'MUNUS: female' },
  'munus': { glyph: '\u{12197}', gloss: 'MUNUS: female' },
  'kur': { glyph: '\u{1217D}', gloss: 'KUR: land' },
  'uru': { glyph: '\u{1231D}', gloss: 'URU: city' },
  'gish': { glyph: '\u{12117}', gloss: 'GISH: wood/tree' },
  'giz': { glyph: '\u{12117}', gloss: 'GISH: wood/tree' },
  'lu': { glyph: '\u{12195}', gloss: 'LU: profession/person' },
  'lu2': { glyph: '\u{12195}', gloss: 'LU: profession/person' },
  'na4': { glyph: '\u{121D0}', gloss: 'NA4: stone' },
  'ki': { glyph: '\u{1215E}', gloss: 'KI: place (postposed)' },
  'ni': { glyph: '\u{121EF}', gloss: 'NI: oil vessel' },
  'im': { glyph: '\u{12150}', gloss: 'IM: clay/wind' },
  'ku6': { glyph: '\u{12129}', gloss: 'KU6: fish' },
  'mushen': { glyph: '\u{12137}', gloss: 'MUSHEN: bird' },
  'tug2': { glyph: '\u{12111}', gloss: 'TUG2: cloth' },
  'urudu': { glyph: '\u{121FA}', gloss: 'URUDU: copper' },
  'sar': { glyph: '\u{12279}', gloss: 'SAR: plant' },
};

// Numbers. Cuneiform uses a sexagesimal (base-60) mixed with base-10.
// Common signs 1..9, 10, 20, 30, 60.
export const NUMBER: Record<string, SignEntry> = {
  '1': { glyph: '\u{12079}', gloss: 'DISH (1)' },
  '2': { glyph: '\u{12415}', gloss: 'MIN (2)' },
  '3': { glyph: '\u{12416}', gloss: 'ESH (3)' },
  '4': { glyph: '\u{12417}', gloss: 'LIMMU (4)' },
  '5': { glyph: '\u{12418}', gloss: 'YA (5)' },
  '6': { glyph: '\u{12419}', gloss: 'ASH (6)' },
  '7': { glyph: '\u{1241A}', gloss: 'IMIN (7)' },
  '8': { glyph: '\u{1241B}', gloss: 'USSU (8)' },
  '9': { glyph: '\u{1241C}', gloss: 'ILIMMU (9)' },
  '10': { glyph: '\u{1230B}', gloss: 'U (10)' },
  '20': { glyph: '\u{12467}', gloss: '20' },
  '30': { glyph: '\u{12468}', gloss: '30' },
  '60': { glyph: '\u{12079}', gloss: 'GESH (60, same shape as 1)' },
};

// English-word to determinative lookup.
// Used by the English pipeline to auto-tag common nouns.
export const DETERMINATIVE_BY_WORD: Record<string, string> = {
  'god': 'd',
  'goddess': 'd',
  'divine': 'd',
  'lord': 'd',
  'king': 'lugal',
  'queen': 'nin',
  'man': 'm',
  'woman': 'f',
  'lady': 'nin',
  'land': 'kur',
  'country': 'kur',
  'mountain': 'kur',
  'city': 'uru',
  'town': 'uru',
  'wood': 'gish',
  'tree': 'gish',
  'stone': 'na4',
  'fish': 'ku6',
  'bird': 'mushen',
  'copper': 'urudu',
  'cloth': 'tug2',
  'garment': 'tug2',
  'plant': 'sar',
};

// English words that map directly to a known logogram (a small dictionary).
export const LOGOGRAM_BY_ENGLISH: Record<string, string> = {
  'king': 'LUGAL',
  'god': 'DINGIR',
  'lord': 'EN',
  'lady': 'NIN',
  'queen': 'NIN',
  'house': 'E',
  'temple': 'E',
  'city': 'URU',
  'land': 'KUR',
  'mountain': 'KUR',
  'water': 'A',
  'father': 'AD',
  'mother': 'AMA',
  'son': 'DUMU',
  'daughter': 'DUMU',
  'day': 'UD',
  'sun': 'UTU',
  'sky': 'AN',
  'heaven': 'AN',
  'earth': 'KI',
  'life': 'TI',
  'name': 'MU',
  'year': 'MU',
  'hand': 'SHU',
  'head': 'SAG',
  'heart': 'SHA',
  'eye': 'IGI',
  'mouth': 'KA',
  'bull': 'GUD',
  'sheep': 'UDU',
  'grain': 'SHE',
  'barley': 'SHE',
  'reed': 'GI',
  'tree': 'GISH',
  'wood': 'GISH',
  'stone': 'NA',
  'fish': 'HA',
  'bird': 'HU',
  'dog': 'UR',
  'great': 'GAL',
  'small': 'TUR',
  'good': 'DUG',
  'evil': 'HUL',
  'true': 'ZI',
  'to go': 'DU',
  'come': 'DU',
  'give': 'SUM',
  'know': 'ZU',
  'speak': 'DUG',
  'write': 'SAR',
};

// Palette entries grouped by category, used by SignPalette in cuneiform mode.
export interface PaletteEntry {
  key: string;
  glyph: string;
  label: string;
}

export const PALETTE: Record<string, PaletteEntry[]> = {
  'Vowels': ['a', 'e', 'i', 'u'].map(k => ({
    key: k, glyph: SYLLABIC[k].glyph, label: `${k} - ${SYLLABIC[k].gloss}`
  })),
  'Common syllables': [
    'ba', 'bi', 'bu', 'da', 'di', 'du', 'ga', 'gi', 'gu', 'ha', 'hi', 'hu',
    'ka', 'ki', 'ku', 'la', 'li', 'lu', 'ma', 'mi', 'mu', 'na', 'ne', 'ni', 'nu',
    'pa', 'pi', 'pu', 'ra', 'ri', 'sa', 'si', 'su', 'sha', 'she', 'shu',
    'ta', 'te', 'ti', 'tu', 'za', 'zi', 'zu',
  ].map(k => ({ key: k, glyph: SYLLABIC[k].glyph, label: `${k} - ${SYLLABIC[k].gloss}` })),
  'VC and CVC': [
    'an', 'ab', 'al', 'am', 'ash', 'ib', 'in', 'ish', 'ud', 'un', 'ur', 'ush',
    'bad', 'bar', 'dam', 'dan', 'dub', 'gal', 'gan', 'gar', 'kal', 'kur',
    'lam', 'lil', 'mah', 'mes', 'nam', 'nin', 'nun', 'sag', 'sar', 'shar',
    'shu', 'tab', 'tar', 'tur',
  ].map(k => ({ key: k, glyph: SYLLABIC[k].glyph, label: `${k} - ${SYLLABIC[k].gloss}` })),
  'Common logograms': [
    'LUGAL', 'DINGIR', 'AN', 'EN', 'NIN', 'LU', 'MUNUS', 'DUMU', 'AD',
    'E', 'URU', 'KUR', 'KI', 'A', 'UTU', 'UD', 'MU', 'GAL', 'TUR',
    'GUD', 'HA', 'HU', 'UR', 'GISH', 'NA', 'SHE', 'TI', 'ZI', 'ZU',
    'SHU', 'SAG', 'IGI', 'KA', 'SHA', 'ME', 'MES', 'PA', 'RA',
  ].filter(k => LOGOGRAM[k]).map(k => ({
    key: k, glyph: LOGOGRAM[k].glyph, label: `${k} - ${LOGOGRAM[k].gloss}`
  })),
  'Determinatives': Object.entries(DETERMINATIVE).map(([k, v]) => ({
    key: `{${k}}`, glyph: v.glyph, label: `{${k}} - ${v.gloss}`
  })),
  'Numbers': Object.entries(NUMBER).map(([k, v]) => ({
    key: k, glyph: v.glyph, label: `${k} - ${v.gloss}`
  })),
};

// Look up a sign by any of: exact ATF value, uppercase logogram, {det}, or number.
export function lookupSign(token: string): string | null {
  if (token.startsWith('{') && token.endsWith('}')) {
    const key = token.slice(1, -1);
    return DETERMINATIVE[key]?.glyph ?? null;
  }
  if (NUMBER[token]) return NUMBER[token].glyph;
  // Uppercase implies logogram
  if (/^[A-Z]/.test(token) && LOGOGRAM[token]) return LOGOGRAM[token].glyph;
  // Lowercase (syllabic)
  const lower = token.toLowerCase();
  if (SYLLABIC[lower]) return SYLLABIC[lower].glyph;
  // Try uppercase interpretation as a fallback
  const upper = token.toUpperCase();
  if (LOGOGRAM[upper]) return LOGOGRAM[upper].glyph;
  return null;
}
